use tk_insight;

INSERT INTO tk_insight.tk_users (userid, password, name, creationdate, souserid, asfuserid, hruserid) VALUES ('user1', 'password1', 'User 1', '2015-09-25 00:00:00', '9', 'antelder', '');
INSERT INTO tk_insight.tk_users (userid, password, name, creationdate, souserid, asfuserid, hruserid) VALUES ('user2', 'password2', 'User 2', '2015-09-25 00:00:00', '47', 'apurtell', '');
INSERT INTO tk_insight.tk_users (userid, password, name, creationdate, souserid, asfuserid, hruserid) VALUES ('user3', 'password3', 'User 3', '2015-09-25 00:00:00', '4', 'akarasulu', '');
INSERT INTO tk_insight.tk_users (userid, password, name, creationdate, souserid, asfuserid, hruserid) VALUES ('user4', 'password4', 'User 4', '2015-09-25 00:00:00', '37', 'dblevins', '');
INSERT INTO tk_insight.tk_users (userid, password, name, creationdate, souserid, asfuserid, hruserid) VALUES ('user5', 'password5', 'User 5', '2015-09-25 00:00:00', '7', 'dirkx', '');